### ISSUE TITLE
Why to reference node type def?

### ISSUE THREAD

**Issue by MarkChrisLevy** [gfmio/ts-error#1]
Hi @gfmio , thanks for great lib, but one question - is it really necessary to reference node type definition in lib declarations?
```
/// <reference types="node" />
```
It causing small issues, when requiring your lib in browser app - node typedef is referenced and because of that it is a must to make a dependency to ```@types/node``` and additionally node typedef changes signatures of some methods (e.g. setTimeout).

**Comment by gfmio** [comment]
Hi @MarkChrisLevy! Thanks for filing this bug report. You're right, this shouldn't make a difference. I'm fixing this now.

**Comment by MarkChrisLevy** [comment]
@gfmio Thanks!
